name = "Cuas"
uuid = "5e7100d4-50d8-4520-bbe7-ebd075d2e2c0"
authors = ["Irene Ndindabahizi"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
